"""new fields in user model

Revision ID: 718c5aa55245
Revises: b4eb35f464aa
Create Date: 2020-01-13 22:12:17.360315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718c5aa55245'
down_revision = 'b4eb35f464aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
